{{ if and .Values.global.configuration.enabled .Values.configuration.enabled .Values.configuration.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "openzaak.configName" . }}
  labels:
    {{- include "openzaak.configLabels" . | nindent 4 }}
spec:
  schedule: {{ .Values.configuration.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.configuration.cronjob.historyLimit }}
  failedJobsHistoryLimit: {{ .Values.configuration.cronjob.historyLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "openzaak.configLabels" . | nindent 12 }}
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "openzaak.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ .Values.existingSecret | default (include "openzaak.fullname" .) }}
                - configMapRef:
                    name: {{ include "openzaak.fullname" . }}
              env:
                {{- if .Values.extraEnvVars }}
                {{- include "openzaak.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 16 }}
                {{- end }}
              resources:
              {{- toYaml .Values.configuration.cronjob.resources | nindent 16 }}
              command:
                - "/bin/bash"
                - "-c"
              args:
              - |
                /setup_configuration.sh
                {{- if .Values.configuration.notificaties.registerKanalen }}
                /app/src/manage.py register_kanalen
                {{- end }}
              volumeMounts:
                - name: media
                  mountPath: /app/private-media
                  subPath: {{ .Values.persistence.privateMediaMountSubpath | default "openzaak/private_media" }}
                - name: media
                  mountPath: /app/media
                  subPath: {{ .Values.persistence.mediaMountSubpath  | default "openzaak/media" }}
                {{- if .Values.extraVolumeMounts }}
                {{- include "openzaak.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $ ) | nindent 16 }}
                {{- end }}
          volumes:
            - name: media
              persistentVolumeClaim:
              {{- if .Values.persistence.enabled }}
                claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "openzaak.fullname" . }}{{- end }}
              {{- else }}
              emptyDir: { }
              {{- end }}
            {{- if .Values.extraVolumes }}
            {{- include "openzaak.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $ ) | nindent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
