{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openzaak.fullname" . }}
  labels:
    {{- include "openzaak.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.settings.database.password | toString | quote }}
  SECRET_KEY: {{ .Values.settings.secretKey | toString |  quote }}
  FLOWER_BASIC_AUTH:  {{ .Values.settings.flower.basicAuth | toString | quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVER_URL: {{ .Values.settings.elasticapm.url | toString |  quote }}
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.settings.elasticapm.token | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.email.password }}
  EMAIL_HOST_PASSWORD: {{ .Values.settings.email.password | toString | quote }}
  {{- end }}
  {{ if and .Values.global.configuration.enabled .Values.configuration.enabled -}}
  {{ if .Values.configuration.notificatiesAuthorization.enabled }}
  NOTIF_OPENZAAK_SECRET: {{ .Values.global.configuration.notificatiesOpenzaakSecret | default .Values.configuration.notificatiesAuthorization.notifcationOpenzaakSecret  | toString | quote }}
  {{- end }}
  {{ if .Values.configuration.notificaties.enabled }}
  OPENZAAK_NOTIF_SECRET: {{ .Values.global.configuration.openzaakNotificatiesSecret | default .Values.configuration.notificaties.openzaakNotificationSecret | toString | quote }}
  {{- end }}
  {{- end }}
  {{ if .Values.configuration.superuser.username }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.configuration.superuser.password | toString | quote }}
  {{- end }}
{{- end }}
