apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "objecten.fullname" . }}
  labels:
    {{- include "objecten.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings.djangoSettingsModule | toString | quote }}
  ENVIRONMENT: {{ .Values.settings.environment | default (include "objecten.fullname" .) }}
  ALLOWED_HOSTS: "{{ include "objecten.fullname" . }},{{ include "objecten.fullname" . }}.{{ .Release.Namespace }},{{ .Values.settings.allowedHosts | replace " " "" | toString }}"
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  DB_HOST: {{ .Values.settings.database.host | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  {{ if .Values.settings.debug }}
  DEBUG: "True"
  {{- end }}
  TWO_FACTOR_FORCE_OTP_ADMIN: {{ if .Values.settings.twoFactorAuthentication.forceOtpAdmin }}"True"{{ else }}"False"{{ end }}
  TWO_FACTOR_PATCH_ADMIN: {{ if .Values.settings.twoFactorAuthentication.patchAdmin }}"True"{{ else }}"False"{{ end }}
  IS_HTTPS: {{ if .Values.settings.isHttps }}"True"{{ else }}"False"{{ end }}
  EMAIL_HOST: {{ .Values.settings.email.host | toString | quote }}
  EMAIL_PORT: {{ .Values.settings.email.port | toString | quote }}
  {{- if .Values.settings.email.username }}
  EMAIL_HOST_USER: {{ .Values.settings.email.username | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.useTLS }}
  EMAIL_USE_TLS: "True"
  {{- end }}
  {{- if .Values.settings.email.defaultFrom }}
  DEFAULT_FROM_EMAIL: {{ .Values.settings.email.defaultFrom | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVICE_NAME: {{ .Values.settings.elasticapm.serviceName | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.master }}
  UWSGI_MASTER:  {{ if .Values.settings.uwsgi.master }}"1"{{ else }}"0"{{ end }}
  {{- end }}
  {{- if .Values.settings.uwsgi.threads }}
  UWSGI_THREADS: {{ .Values.settings.uwsgi.threads  | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.processes }}
  UWSGI_PROCESSES: {{ .Values.settings.uwsgi.processes | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.maxRequests }}
  UWSGI_MAX_REQUESTS: {{ .Values.settings.uwsgi.maxRequests | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.harakiri }}
  UWSGI_HARAKIRI: {{ .Values.settings.uwsgi.harakiri | toString | quote }}
  {{- end }}
