apiVersion: v2
name: openinwoner
description: Platform voor gemeenten en overheden om producten inzichtelijker en toegankelijker te maken voor inwoners.

type: application
version: 0.9.6
appVersion: "1.7.1"

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: elasticsearch
    version: 19.5.11
    repository: https://charts.bitnami.com/bitnami
    tags:
      - elasticsearch
