apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobjecttypes.fullname" . }}
  labels:
    {{- include "openobjecttypes.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings.djangoSettingsModule | toString | quote }}
  ENVIRONMENT: {{ .Values.settings.environment | default (include "openobjecttypes.fullname" .) }}
  ALLOWED_HOSTS: "{{ include "openobjecttypes.fullname" . }},{{ include "openobjecttypes.fullname" . }}.{{ .Release.Namespace }},{{ .Values.settings.allowedHosts | toString }}"
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  DB_HOST: {{ .Values.settings.database.host | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  DEBUG: {{ if .Values.settings.debug }}"True"{{ else }}"False"{{ end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVICE_NAME: {{ .Values.settings.elasticapm.serviceName | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.master }}
  UWSGI_MASTER:  {{ if .Values.settings.uwsgi.master }}"1"{{ else }}"0"{{ end }}
  {{- end }}
  {{- if .Values.settings.uwsgi.threads }}
  UWSGI_THREADS: {{ .Values.settings.uwsgi.threads  | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.processes }}
  UWSGI_PROCESSES: {{ .Values.settings.uwsgi.processes | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.maxRequests }}
  UWSGI_MAX_REQUESTS: {{ .Values.settings.uwsgi.maxRequests | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.harakiri }}
  UWSGI_HARAKIRI: {{ .Values.settings.uwsgi.harakiri | toString | quote }}
  {{- end }}
