apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobjecttypes.fullname" . }}
  labels:
    {{- include "openobjecttypes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "openobjecttypes.selectorLabels" . | nindent 4 }}
