{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openforms.fullname" . }}
  labels:
    {{- include "openforms.labels" . | nindent 4 }}
stringData:
  {{- if .Values.tags.postgresql }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | toString | quote }}
  {{ else }}
  DB_PASSWORD: {{ .Values.settings.database.password | toString | quote }}
  {{- end }}
  SECRET_KEY: {{ .Values.settings.secretKey | toString |  quote }}
  FLOWER_BASIC_AUTH:  {{ .Values.settings.flower.basicAuth | toString | quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}
  ELASTIC_APM_SERVER_URL: {{ .Values.settings.elasticapm.url | toString |  quote }}
  ELASTIC_APM_SECRET_TOKEN: {{ .Values.settings.elasticapm.token | toString |  quote }}
  {{- end }}
  {{- if .Values.settings.email.password }}
  EMAIL_HOST_PASSWORD: {{ .Values.settings.email.password | toString | quote }}
  {{- end }}
{{- end }}
