apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openforms.fullname" . }}
  labels:
    {{- include "openforms.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings.djangoSettingsModule | toString | quote }}
  {{- if .Values.settings.baseUrl }}
  BASE_URL: {{ .Values.settings.baseUrl | toString | quote }}
  {{- end }}
  {{- if .Values.settings.useXForwardedHost }}
  USE_X_FORWARDED_HOST: "True"
  {{- end }}  
  ENVIRONMENT: {{ .Values.settings.environment | default (include "openforms.fullname" .) }}
  CORS_ALLOW_ALL_ORIGINS: {{ if .Values.settings.cors.allowAllOrigins }}"True"{{ else }}"False"{{ end }}
  {{ if .Values.settings.cors.allowedOrigins }}
  CORS_ALLOWED_ORIGINS: {{  join "," .Values.settings.cors.allowedOrigins | toString }}
  {{ end }}
  {{ if .Values.settings.csrf.trustedOrigins }}
  CSRF_TRUSTED_ORIGINS: {{ join "," .Values.settings.csrf.trustedOrigins | toString | quote }}
  {{ end }} 
  {{ if .Values.settings.cookieSamesite }}
  SESSION_COOKIE_SAMESITE: {{ .Values.settings.cookieSamesite | toString | }}
  CSRF_COOKIE_SAMESITE: {{ .Values.settings.cookieSamesite | toString | }}
  LANGUAGE_COOKIE_SAMESITE: {{ .Values.settings.cookieSamesite | toString | }}
  {{ end }}
  CSP_REPORTS_SAVE: {{ if .Values.settings.csp.reportSave }}"True"{{ else }}"False"{{ end }}
  CSP_EXTRA_DEFAULT_SRC: {{ join "," .Values.settings.csp.extraDefaultSrc | toString | quote }}
  CSP_EXTRA_IMG_SRC: {{ join "," .Values.settings.csp.extraImgSrc | toString | quote }}
  {{- if .Values.extraVerifyCerts }}
  EXTRA_VERIFY_CERTS: {{ .Values.extraVerifyCerts| toString | quote }}
  {{- end }}  
  ALLOWED_HOSTS: "{{ include "openforms.fullname" . }},{{ include "openforms.fullname" . }}.{{ .Release.Namespace }},{{ .Values.settings.allowedHosts | toString }}"
  {{- if .Values.tags.redis }}
  CACHE_DEFAULT: "{{ include "openforms.fullname" . }}-redis-master.{{ .Release.Namespace }}:6379/0"
  CACHE_AXES: "{{ include "openforms.fullname" . }}-redis-master.{{ .Release.Namespace }}:6379/0"
  CACHE_PORTALOCKER: "{{ include "openforms.fullname" . }}-redis-master.{{ .Release.Namespace }}:6379/0"
  CELERY_BROKER_URL: "redis://{{ include "openforms.fullname" . }}-redis-master.{{ .Release.Namespace }}:6379/1"
  CELERY_RESULT_BACKEND: "redis://{{ include "openforms.fullname" . }}-redis-master.{{ .Release.Namespace }}:6379/1"
  {{ else }}
  CACHE_DEFAULT: {{ .Values.settings.cache.default | toString | quote }}
  CACHE_AXES: {{ .Values.settings.cache.axes | toString | quote }}
  CACHE_PORTALOCKER: {{ .Values.settings.cache.default | toString | quote }}
  CELERY_BROKER_URL: {{ .Values.settings.celery.brokerUrl | toString | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.settings.celery.resultBackendl | toString | quote }}
  {{- end }}
  CELERY_LOGLEVEL:  {{ .Values.settings.celery.logLevel | upper | toString | quote }}
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  DB_HOST: {{ .Values.settings.database.host | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  DEBUG: {{ if .Values.settings.debug }}"True"{{ else }}"False"{{ end }}
  NUM_PROXIES: {{ .Values.settings.numProxies | toString | quote }}  
  IS_HTTPS: {{ if .Values.settings.isHttps }}"True"{{ else }}"False"{{ end }}
  FLOWER_URL_PREFIX: {{ .Values.settings.flower.urlPrefix | toString | quote }}  
  EMAIL_HOST: {{ .Values.settings.email.host | toString | quote }}
  EMAIL_PORT: {{ .Values.settings.email.port | toString | quote }}
  {{- if .Values.settings.email.username }}
  EMAIL_HOST_USER: {{ .Values.settings.email.username | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.useTLS }}
  EMAIL_USE_TLS: "True"
  {{- end }} 
  {{- if .Values.settings.email.defaultFrom }}
  DEFAULT_FROM_EMAIL: {{ .Values.settings.email.defaultFrom | toString | quote }}
  {{- end }}
  {{- if .Values.settings.elasticapm.url }}  
  ELASTIC_APM_SERVICE_NAME: {{ .Values.settings.elasticapm.serviceName | toString |  quote }}
  {{- end }}
  TWO_FACTOR_FORCE_OTP_ADMIN: {{ if .Values.settings.twoFactorAuthentication }}"True"{{ else }}"False"{{ end }}
  TWO_FACTOR_PATCH_ADMIN: {{ if .Values.settings.twoFactorAuthentication }}"True"{{ else }}"False"{{ end }}
  CELERY_WORKER_CONCURRENCY: {{ .Values.worker.concurrency | toString | quote }}
  MAX_FILE_UPLOAD_SIZE: {{ .Values.settings.maxFileUpload | toString | quote }}
  ENABLE_THROTTLING: {{ if .Values.settings.throttling.enable }}"True"{{ else }}"False"{{ end }}
  {{- if .Values.settings.throttling.rateAnonymous }}
  THROTTLE_RATE_ANON: {{ .Values.settings.throttling.rateAnonymous | toString | quote }}
  {{- end }}
  {{- if .Values.settings.throttling.rateUser }}
  THROTTLE_RATE_USER: {{ .Values.settings.throttling.rateUser | toString | quote }}
  {{- end }}
  {{- if .Values.settings.throttling.ratePolling }}
  THROTTLE_RATE_POLLING: {{ .Values.settings.throttling.ratePolling | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.master }}
  UWSGI_MASTER:  {{ if .Values.settings.uwsgi.master }}"1"{{ else }}"0"{{ end }}
  {{- end }}
  {{- if .Values.settings.uwsgi.threads }}
  UWSGI_THREADS: {{ .Values.settings.uwsgi.threads  | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.processes }}
  UWSGI_PROCESSES: {{ .Values.settings.uwsgi.processes | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.maxRequests }}
  UWSGI_MAX_REQUESTS: {{ .Values.settings.uwsgi.maxRequests | toString | quote }}
  {{- end }}
  {{- if .Values.settings.uwsgi.harakiri }}
  UWSGI_HARAKIRI: {{ .Values.settings.uwsgi.harakiri | toString | quote }}
  {{- end }}
  