apiVersion: v1
kind: Service
metadata:
  name: {{ include "openforms.fullname" . }}
  labels:
    {{- include "openforms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "openforms.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openforms.nginxFullname" . }}
  labels:
    {{- include "openforms.nginxLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "openforms.nginxSelectorLabels" . | nindent 4 }}
---
{{- if .Values.flower.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openforms.flowerFullname" . }}
  labels:
    {{- include "openforms.flowerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "openforms.flowerSelectorLabels" . | nindent 4 }}
{{- end }}
