{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openarchiefbeheer.fullname" . }}
  labels:
    {{- include "openarchiefbeheer.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.settings.database.password | toString | quote }}
  SECRET_KEY: {{ .Values.settings.secretKey | toString |  quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | quote }}
  {{- end }}
{{- end }}
