{{ if .Values.settings.cleanOldNotifications.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "opennotificaties.fullname" . }}-clean-old-notificatons
  labels:
    {{- include "opennotificaties.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.settings.cleanOldNotifications.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.settings.cleanOldNotifications.cronjob.historyLimit }}
  failedJobsHistoryLimit: {{ .Values.settings.cleanOldNotifications.cronjob.historyLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "opennotificaties.labels" . | nindent 12 }}
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "opennotificaties.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ .Values.existingSecret | default (include "opennotificaties.fullname" .) }}
                - configMapRef:
                    name: {{ include "opennotificaties.fullname" . }}
              env:
                {{- if .Values.extraEnvVars }}
                {{- include "opennotificaties.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
                {{- end }}
              resources:
              {{- toYaml .Values.settings.cleanOldNotifications.cronjob.resources | nindent 16 }}
              command:
                - "/bin/bash"
                - "-c"
                -  /app/src/manage.py clean_old_notifications
          {{- with .Values.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
